### ISSUE TITLE
Issue when cross compiling

### ISSUE THREAD

**Issue by mrcancer91** [alexanderchuranov/Metaresc#2] opened 2020-02-13 08:30 UTC
Hello, 
First of all, I want to thank you for the amazing work. I'm trying to use your Metaresc in my embedded project. I cross-compile Metaresc using below options: 
```
--host=mips-unknown-linux-uclibc --includedir=$(KERNEL_DIR)/include  CC=mips-unknown-linux-uclibc-gcc CFLAGS="-g -O2 -Wall -msoft-float -fomit-frame-pointer -mips32r2 -muclibc"
```
The first error I got 
```
/usr/include/libxml2/libxml/encoding.h:28:19: error: iconv.h: No such file or directory
```
I resolve it by adding `-I/usr/include/iconv_hook/` (where I found the iconv.h) into CFLAGS 
But got these error: 

```
In file included from metaresc.c:25:
./mr_save.h:6: error: unknown field 'enum_param' specified in initializer
./mr_save.h:6: error: unknown field 'mr_type_effective' specified in initializer
In file included from metaresc.c:30:
./mr_protos.h:7: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:7: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:15: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:15: error: unknown field 'mr_type_effective' specified in initializer
cc1: warnings being treated as errors
./mr_protos.h:15: error: initialization makes pointer from integer without a cast
./mr_protos.h:26: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:26: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:26: error: initialization makes pointer from integer without a cast
./mr_protos.h:88: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:88: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:88: error: initialization makes pointer from integer without a cast
./mr_protos.h:126: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:126: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:133: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:133: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:133: error: initialization makes pointer from integer without a cast
./mr_protos.h:138: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:138: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:138: error: initialization makes pointer from integer without a cast
./mr_protos.h:145: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:145: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:152: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:152: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:157: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:157: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:165: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:165: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:171: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:171: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:179: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:179: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:181: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:181: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:183: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:183: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:185: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:185: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:187: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:187: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:189: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:189: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:194: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:194: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:194: error: initialization makes pointer from integer without a cast
./mr_protos.h:204: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:204: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:210: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:210: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:218: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:218: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:223: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:223: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:229: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:229: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:247: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:247: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:256: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:256: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:281: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:281: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:285: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:285: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:292: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:292: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:296: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:296: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:315: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:315: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:322: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:322: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:329: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:329: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:335: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:335: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:340: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:340: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:345: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:345: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:345: error: initialization makes pointer from integer without a cast
./mr_protos.h:355: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:355: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:368: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:368: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:375: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:375: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:379: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:379: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:399: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:399: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:399: error: initialization makes pointer from integer without a cast
./mr_protos.h:404: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:404: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:413: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:413: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:420: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:420: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:425: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:425: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:427: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:427: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:429: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:429: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:435: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:435: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:440: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:440: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:448: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:448: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:461: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:461: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:463: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:463: error: unknown field 'mr_type_effective' specified in initializer
./mr_protos.h:465: error: unknown field 'enum_param' specified in initializer
./mr_protos.h:465: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:33: error: unknown field 'enum_param' specified in initializer
metaresc.c:33: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:33: error: initialization makes pointer from integer without a cast
metaresc.c:35: error: unknown field 'enum_param' specified in initializer
metaresc.c:35: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:35: error: initialization makes pointer from integer without a cast
metaresc.c:36: error: unknown field 'enum_param' specified in initializer
metaresc.c:36: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:36: error: initialization makes pointer from integer without a cast
metaresc.c:37: error: unknown field 'enum_param' specified in initializer
metaresc.c:37: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:37: error: initialization makes pointer from integer without a cast
metaresc.c:38: error: unknown field 'enum_param' specified in initializer
metaresc.c:38: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:38: error: initialization makes pointer from integer without a cast
metaresc.c:39: error: unknown field 'enum_param' specified in initializer
metaresc.c:39: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:39: error: initialization makes pointer from integer without a cast
metaresc.c:40: error: unknown field 'enum_param' specified in initializer
metaresc.c:40: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:40: error: initialization makes pointer from integer without a cast
metaresc.c:41: error: unknown field 'enum_param' specified in initializer
metaresc.c:41: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:41: error: initialization makes pointer from integer without a cast
metaresc.c:42: error: unknown field 'enum_param' specified in initializer
metaresc.c:42: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:42: error: initialization makes pointer from integer without a cast
metaresc.c:43: error: unknown field 'enum_param' specified in initializer
metaresc.c:43: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:43: error: initialization makes pointer from integer without a cast
metaresc.c:44: error: unknown field 'enum_param' specified in initializer
metaresc.c:44: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:44: error: initialization makes pointer from integer without a cast
metaresc.c:45: error: unknown field 'enum_param' specified in initializer
metaresc.c:45: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:45: error: initialization makes pointer from integer without a cast
metaresc.c:46: error: unknown field 'enum_param' specified in initializer
metaresc.c:46: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:46: error: initialization makes pointer from integer without a cast
metaresc.c:47: error: unknown field 'enum_param' specified in initializer
metaresc.c:47: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:47: error: initialization makes pointer from integer without a cast
metaresc.c:48: error: unknown field 'enum_param' specified in initializer
metaresc.c:48: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:48: error: initialization makes pointer from integer without a cast
metaresc.c:49: error: unknown field 'enum_param' specified in initializer
metaresc.c:49: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:49: error: initialization makes pointer from integer without a cast
metaresc.c:50: error: unknown field 'enum_param' specified in initializer
metaresc.c:50: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:50: error: initialization makes pointer from integer without a cast
metaresc.c:51: error: unknown field 'enum_param' specified in initializer
metaresc.c:51: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:51: error: initialization makes pointer from integer without a cast
metaresc.c:52: error: unknown field 'enum_param' specified in initializer
metaresc.c:52: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:52: error: initialization makes pointer from integer without a cast
metaresc.c:53: error: unknown field 'enum_param' specified in initializer
metaresc.c:53: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:53: error: initialization makes pointer from integer without a cast
metaresc.c:54: error: unknown field 'enum_param' specified in initializer
metaresc.c:54: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:54: error: initialization makes pointer from integer without a cast
metaresc.c:55: error: unknown field 'enum_param' specified in initializer
metaresc.c:55: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:55: error: initialization makes pointer from integer without a cast
metaresc.c:56: error: unknown field 'enum_param' specified in initializer
metaresc.c:56: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:56: error: initialization makes pointer from integer without a cast
metaresc.c:57: error: unknown field 'enum_param' specified in initializer
metaresc.c:57: error: unknown field 'mr_type_effective' specified in initializer
metaresc.c:57: error: initialization makes pointer from integer without a cast
make[2]: *** [metaresc.lo] Error 1
```

System info: 
```
OS: Ubuntu 12.04
automake (GNU automake) 1.11.3
libtool (GNU libtool) 2.4.2
autoconf (GNU Autoconf) 2.68
pkg-config: v0.26
flex 2.5.35
bison (GNU Bison) 2.5
xml12 version: 2.7.8.dfsg-5.1ubuntu4.17 (Depends: libxml2 (= 2.7.8.dfsg-5.1ubuntu4.17))
```
Could you please give me some hints about this?
Thanks in advance and I really appreciate your work & effort!

**Comment by hnarkaytis** [comment] 2020-02-13 11:53
Duy,
  It looks like unnamed unions are not fully supported by your version of GCC (btw, what version do you use for cross compilation?). From other hand anonymous unions were added to Metaresc in 2012 and Ubuntu 12.04 was released in 2014, i.e. it should work.
  I will need to reproduce your env for troubleshooting. If you have VM image that could help.

  Another way to troubleshoot is to use your env. I.e. I will need your help to examine output of preprocessor and compiler features.
  The error message indicates that anonymous union here https://github.com/alexanderchuranov/Metaresc/blob/master/src/mr_protos.h#L304 was not correctly either rendered by CPP or incorrectly interpreted by GCC. To double check this I need you to run mr_protos.h through preprocessor and share output with me.
gcc -E -I. `xml2-config --cflags` mr_protos.h > mr_protos.hh
  Resulting mr_protos.hh will be rather big (about 2.5Mb), i.e. it would be better to share it via external file hosting like google drive.

  Also please create a dummy .c file with the following type definition:
struct x_t { 
  char type_specific[0]; 
  union { 
     int int_param; 
     long long_param; 
  }
};
  Try to compile it with you cross-gcc and let me know how it worked out.

  Other notice - libxml2 is optional for XML support, i.e. you could disable libxml2 at configuration stage and library will fallback on embedded XML serialization and parsing.

HHN.

**Comment by mrcancer91** [comment] 2020-02-14 02:57
@hnarkaytis Thank you for the quick reply.
I created a dummy.c with below content 
```C
#include<stdio.h>

struct x_t {
	char type_specific[0];
	union {
		int int_param;
		long long_param;
	}
};

int main(){
	printf("Hello world");
}
```
And below is the output when compile using my cross-compiler gcc
```
$ mips-unknown-linux-uclibc-gcc -c dummy.c
dummy.c:9: error: expected identifier or '(' before '}' token
dummy.c:11: error: expected ':', ',', ';', '}' or '__attribute__' before '{' token
$
```
I add at line 9 one semicolon `;` after the `}` of `union` declaration and the cross compile runs with no issue. 
I think the issue could come from my cross-compiler's behavior. Is there any way that can resolve this issue?
Does this

**Comment by hnarkaytis** [comment] 2020-02-14 08:42
Duy,
  It all looks correct. Rendering and transparent union support is ok.
  Let's double check initialization of transparent union. Add to main() in dummy.c the following:
  struct x_t __attribute__((unused)) x = {
    .long_param = 0,
  };

  The essence of error message is that compiler can't initialize field in struct which is declared as anonymous union. So previous checks showed that type with anonymous union was rendered correctly and compiler can handle those types. This check will show if there is a problem in static initialization for this kind of the fields.

  Ubuntu 12 and gcc 4.3.6 are outdated a little bit (9 years since since 2011). Documentation for this version of gcc says that anonymous unions are first class citizens https://gcc.gnu.org/onlinedocs/gcc-4.3.6/gcc/Unnamed-Fields.html, but documentation for latest gcc release https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/Unnamed-Fields.html says that feature was standardized in C11 (which was published in April of 2011). gcc 4.3.6 was released in August of 2011, i.e. there was only only 4 months since C11 finalization.

  The other possible issue might be related to extra compiler flags that I set in configure.ac. Configuration script checks that compiler supports flags -Wno-initializer-overrides -Wno-constant-conversion -Wno-duplicate-decl-specifier. Those flags were added for clang, just because it report warnings for duplicated initializers for structures fields. Those flags are not mandatory for gcc. It should work ok.
 
HHN.

**Comment by mrcancer91** [comment] 2020-02-14 10:26
HHN,

Sorry @hnarkaytis , I had to add a semicolon at line 9 (after the `}` of the union definition), so what do you mean by `transparent union support is ok` ?

Added more content into `dummy.c` as below
```C
#include<stdio.h>

struct x_t {
	char type_specific[0];
	union {
		int int_param;
		long long_param;
	} ;//Cross compile failed here, adding a semicolon ; can fix compile issue
};

int main(){
	struct x_t attribute((unused)) x = {
	.long_param=0,
	};
	printf("Hello world");
}
```

Running the compile command again
`mips-unknown-linux-uclibc-gcc -c dummyunion.c`

And below is output
```
dummyunion.c: In function 'main':
dummyunion.c:12: error: expected declaration specifiers or '...' before '(' token
dummyunion.c: In function 'attribute':
dummyunion.c:12: error: expected declaration specifiers before 'x'
dummyunion.c:14: error: expected declaration specifiers before ';' token
dummyunion.c:15: error: expected declaration specifiers before 'printf'
dummyunion.c:16: error: expected declaration specifiers before '}' token
dummyunion.c:16: error: expected '{' at end of input
dummyunion.c: In function 'main':
dummyunion.c:16: error: expected declaration or statement at end of input
```

About the compiler support flags -Wno-initializer-overrides -Wno-constant-conversion -Wno-duplicate-decl-specifier, I commented out the part related to those 3 flags then re-run 
```
./autogen.sh && ./configure --host=mips-linux --includedir=/usr/include  CC=mips-unknown-linux-uclibc-gcc CFLAGS="-g -O2 -Wall -I/usr/include/iconv_hook" CPATH=/usr/include/i386-linux-gnu/ LIBXML2=no
```
But the result is still the same. 

Duy.

**Comment by hnarkaytis** [comment] 2020-02-14 11:35
Duy,
  Your dummy.c is exactly what I expected. I missed semicolon just because have not checked code in compiler. Code snippet from my previous comment was formatted by github what's why compilation failed. It should read:

`struct x_t x __attribute__((unused)) = { .long_param = 0, };`

  `__attribute__((unused))` is a way to avoid warning about unused variable. 

  Your configuration params looks correct.
  I've also noticed that you have bison 2+. What would be another issue to solve. Metaresc was ported on bison 3+ some time ago. I.e. will need either to build bison from sources or backport all Metaresc .y files.

HHN.

**Comment by mrcancer91** [comment] 2020-02-15 06:06
HHN,

I switched to another ubuntu 16.04 with 
```
bison 3.0.4
automake 1.15
autoconf 2.69
libtool 2.2.10
```
I rechecked the syntax you noted using 
```
 mips-unknown-linux-uclibc-gcc -E -I. `xml2-config --cflags` mr_protos.h > mr_protos.hh
```
you can check the new file mips-unknown-linux-uclibc-gcc_mr_protos.hh [here](https://drive.google.com/open?id=1XT7LyTG90syW-HSLASrDjp65tqB6Y9RU)

Duy.

**Comment by hnarkaytis** [comment] 2020-02-15 18:59
Duy,
  Ubuntu 16 is much better. I'll be able to reproduce your build env. I'm traveling next couple of days. Will have a chance to look into this next Tuesday.
  Your dummy.c has union name (data) for some reason. Try to compile without it. Copy/paste code below.

```
#include <stdio.h>

struct x_t {
  char type_specific[0];
  union {
    int int_param;
    long long_param;
  };
};

int main(){
  struct x_t x __attribute__((unused)) = { .long_param = 0, };
  printf("Hello world");
}

```
HHN.

**Comment by hnarkaytis** [comment] 2020-02-16 12:51
Duy,
  I've done some tests on Ubuntu 18. 
  For mips cross compilation used buildroot https://buildroot.org/download.html
  There was a minor issue with libxml2 disablement. There was no way to disable it via command line arguments or environment variables, so I added an option to ./configure. There was also an issue with ssize_t type, which was also fixed. Pull latest master from github.
  Here is a command line for proper configuration. You should change full path to CC.
`  ./autogen.sh && ./configure --host=mips-linux --without-libxml2 CC=/home/hnarkaytis/Documents/buildroot/output/host/bin/mipsel-linux-gcc
`
  There is no issue with compiler that you've reported.
  Let me know how you build your cross compiler.

HHN.

**Comment by mrcancer91** [comment] 2020-02-17 09:07
> Your dummy.c has union name (data) for some reason. Try to compile without it. Copy/paste code below.

Copied & pasted your code, below is compile output
```Shell
$ mips-unknown-linux-uclibc-gcc -c dummy.c
dummy.c: In function 'main':
dummy.c:12: error: unknown field 'long_param' specified in initializer
dummy.c:12: warning: excess elements in array initializer
dummy.c:12: warning: (near initialization for 'x.type_specific')
$ 
```

---

> Here is a command line for proper configuration. You should change full path to CC.
> ` ./autogen.sh && ./configure --host=mips-linux --without-libxml2 CC=/home/hnarkaytis/Documents/buildroot/output/host/bin/mipsel-linux-gcc`

The whole `./configure && make`'s output is [here](https://drive.google.com/open?id=1oITsjp5rgirU_lb89y61KW1E6tigNce-)

---

> Let me know how you build your cross compiler.

The cross compiler is provided by our partner in form of binary only. I just add the path into $PATH variable then compile. 

Thank you so much for the effort you invested into this issue!
Duy.

**Comment by hnarkaytis** [comment] 2020-02-18 17:51
Duy,
  Let's make last test before I will tweak library to support this custom compiler.

```
struct x_t {
  int x;
  char type_specific[0];
  union {
    int int_param;
    long long_param;
  };
};

int main ()
{
  struct x_t x __attribute__((unused)) = { .x = 0, };
  return 0;
}

```

  Try to compile this code snippet. This will ensue that initialization of the named field is supported. Without this feature it would be kind a hard to tweak library to work on your compiler.

HHN.

**Comment by mrcancer91** [comment] 2020-02-19 01:59
HHN, 

FYI, the above code snippet of `checking if initialization of the named field is supported` is cross-compiled successfully. 
Glad to know that we can still go futher to resolve this issue!

Duy.

**Comment by mrcancer91** [comment] 2020-02-20 06:54
HHN,
Sorry for the late reply!
I cross-compiled the Metaresc library successfully in 16.04 machine!
However, because the 12.04 lacks the bison v3.x library so currently my only solution is to build the Metaresc in 16.04, then copy the lib & include folder into my source package (which stays insisde the ubuntu 12.04 machine) and cross-compile. Tested with the example [save_json.c](https://github.com/alexanderchuranov/Metaresc/blob/master/examples/save_json.c) running in my embedded device, JSON string generated as expected! 

Thank you very much, HHN! And once again, the Metaresc is amazing!  

Duy.

**Comment by hnarkaytis** [comment] 2020-02-20 19:22
Duy,
  Compilation on Ubuntu 12 is also possible. There are two options: install bison 3+ or disable bison completely (this means that you will get only serialization to JSON, but not deserialization).
  For the first option you will need to download bison sources: `wget http://gnu.mirrors.hoobly.com/bison/bison-3.4.2.tar.xz` Later version has some bug and fails with out of memory.
  Unpack it: `tar -Jxvf bison-3.4.2.tar.xz`
  Compile it: `./configure && make -j`
  Install it into the system (will require sudo rights): `sudo make install`
  Rebuild Metaresc: `make clean ; make -j`

  If deserialization is not required you could just disable bison with configure parameter HAVE_BISON=no. Compilation will fail for examples that are uses deserialization, but library itself will work for serialization.

HHN.

**Closed** 2020-02-20 21:00 UTC
